import axios from 'axios';
import Head from 'next/head';
import Header from '../components/Header';
import Navbar from '../components/Navbar';
import Result from '../components/Result';
import requests from '../utils/requests';

export default function Home({ results }) {
  console.log(results);

  return (
    <div>
      <Head>
        <title>Hulu clone 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Navbar />
      <Result results={results} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const res = await axios.get(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrendings.url
    }`,
  );

  if (!res) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      results: res.data.results,
    },
  };
}
