import Head from 'next/head';
import Header from '../components/Header';
import Navbar from '../components/Navbar';
import Result from '../components/Result';
// import requests from '../utils/requests';

export default function Home({ results }) {
  console.log(results);

  return (
    <div>
      <Head>
        <title>Hulu clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/**header*/}
      <Header />
      {/**navbar*/}
      <Navbar />
      {/**content*/}
      <Result results={results} />
    </div>
  );
}

export async function getServerSideProps(context) {
  //const genre = context.query.genre;

  //const request = await fetch(
  // `https://api.themoviedb.org/3/${
  //    requests[genre]?.url || requests.fetchTrendings.url
  //  }`,
  //).then((res) => res.json());

  const res = await fetch('https://api.themoviedb.org/3/movie/550?api_key=fdfa246ca26ed7a3a5ca359b0cff163c');
  const data = await res.json();

  if (!data) {
    return {
      notFound: true,
    }
  }

  return {
    props: {
      results: data.results || null,
    },
  };
}
